(function(){
  const {TILES,clone,createNormalMap,gameValues,towers}=window.NimTD,canvas=document.getElementById('map'),ctx=canvas.getContext('2d'),stage=document.getElementById('stage'),status=document.getElementById('status');
  const tools=[['Grass',TILES.GRASS,'#3a5533','buildable'],['Path',TILES.PATH,'#6b5b4b','no build'],['Block',TILES.BLOCK,'#53604f','no build'],['Start',TILES.START,'#3d9b62','creep entry'],['End',TILES.END,'#b64b54','creep exit']];
  const effectFields={direct:[],trail:[],flame:[['aoeRadius','Blast radius'],['aoeDuration','Ground flame frames'],['burnDamage','Burn damage']],frost:[['slowDuration','Slow frames']],chain:[['chainCount','Chain targets'],['chainRange','Chain range']],star:[['stunDuration','Stun frames (120 = 2 sec)']],poison:[['poisonDamage','Poison damage'],['poisonDuration','Poison frames'],['poisonStack','Poison stacks']],knockback:[['knockbackForce','Push force']],web:[['webRadius','Web radius'],['webDuration','Web frames'],['webSlow','Web slow amount']],seismic:[['seismicRadius','Shock radius'],['seismicStun','Shock stun frames']],piercing:[['pierceCount','Pierce targets']],radiation:[['radiationStart','Pulse start radius'],['radiationMax','Pulse max radius'],['radiationRate','Pulse expansion rate'],['radiationDuration','Pulse frames']],gravity:[['gravityForce','Gravity force']],laser:[['critChance','Critical chance']],reflect:[['pierceCount','Bounce targets']],summon:[['summonCount','Minion visuals']]};
  const projectilePresets=[
    ['basic','Basic bolt','basic','direct','#ffcc44',{}],['cannon','Cannon shell','cannon','flame','#ff4422',{aoeRadius:55,aoeDuration:180,burnDamage:18}],['sniper','Sniper round','sniper','direct','#00ff88',{}],['tesla','Tesla arc','tesla','chain','#88ccff',{chainCount:3,chainRange:70}],['magic','Energy orb','magic','trail','#cc44ff',{}],['frost','Frost breath','frost','frost','#aaddff',{slowDuration:110}],['star','Star stroke','star','star','#fff0aa',{stunDuration:120}],['laser','Laser beam','laser','laser','#ff4444',{critChance:.3}],['gunner','Gunner bullet','gunner','direct','#ffaa33',{}],['crossbow','Crossbow bolt','crossbow','piercing','#dd9955',{pierceCount:3}],['bomb','Bomb shell','bomb','flame','#222222',{aoeRadius:90,aoeDuration:100,burnDamage:12}],['meteor','Meteor core','meteor','flame','#ff6600',{aoeRadius:110,aoeDuration:240,burnDamage:25}],['inferno','Inferno pulse','inferno','radiation','#ff5500',{radiationStart:30,radiationMax:100,radiationRate:1.5,radiationDuration:60}],['poison','Poison cloud','poison','poison','#66ff44',{poisonDamage:4,poisonDuration:180,poisonStack:1}],['knockback','Knockback blast','knockback','knockback','#ffaa66',{knockbackForce:6}],['web','Web entangle','web','web','#ffeeaa',{webRadius:100,webDuration:160,webSlow:.45}],['seismic','Seismic shock','seismic','seismic','#aa7733',{seismicRadius:130,seismicStun:90}],['gravity','Gravity pull','gravity','gravity','#aa88ff',{gravityForce:4}],['reflect','Reflect prism','reflect','reflect','#88ffff',{pierceCount:3}],['summoner','Summoner spirit','summoner','summon','#88ff44',{summonCount:2}],['temporal','Temporal bolt','temporal','frost','#ccffff',{slowDuration:200}],['aqua','Aqua jet','aqua','knockback','#66bbff',{knockbackForce:3}],['spike','Spike volley','spike','piercing','#dd6633',{pierceCount:4}],['void','Void pulse','void','radiation','#cc66ff',{radiationStart:50,radiationMax:150,radiationRate:3,radiationDuration:100}],['flak','Flak burst','flak','direct','#ddcc88',{}]
  ];
  const models=projectilePresets.map(p=>p[2]),baseFields=[['cost','Cost',50],['damage','Damage',12],['range','Range',140],['fireRate','Rate of fire in frames',60],['projectileSpeed','Projectile speed',7],['projectileSize','Projectile size',3],['projectileCount','Projectiles per shot',1],['spread','Multishot spread',0]];
  const palette=['#000000','#404040','#808080','#c0c0c0','#ffffff','#7f0000','#ff0000','#ff7f00','#ffff00','#7fff00','#00ff00','#007f00','#007f7f','#00ffff','#007fff','#0000ff','#00007f','#7f00ff','#ff00ff','#7f007f','#7f3f00','#bf7f3f','#ffbf7f','#ffdfbf','#3f3f7f','#7f7fbf','#bfbfff','#3f7f7f','#7fbfbf','#bfffff','#3f7f3f','#7fbf7f','#bfffbf','#7f7f3f','#bfbf7f','#ffffbf'];
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api=()=>window.electronAPI?.maps;
  let cfg=loadDraft(),tool=TILES.PATH,towerKey=Object.keys(cfg.towers)[0],view={x:0,y:0,size:28},mouse={paint:false,pan:false,x:0,y:0};
  function normalConfig(){return{version:4,map:createNormalMap(),game:clone(gameValues),towers:clone(towers)}}
  function loadDraft(){try{return JSON.parse(localStorage.getItem('nimtd.editorDraft'))||normalConfig()}catch{return normalConfig()}}
  function tell(message){status.textContent=message}
  function sync(){const m=cfg.map,g=cfg.game;$('width').value=m.width;$('height').value=m.height;$('map-name').value=m.name;$('waves').value=g.waves;$('enemies').value=g.enemiesPerWave;$('enemy-growth').value=g.enemiesPerWaveGrowth;$('starting-gold').value=g.startingGold;$('starting-lives').value=g.startingLives;$('spawn-delay').value=g.baseSpawnDelay;$('minimum-spawn-delay').value=g.minimumSpawnDelay;$('spawn-delay-reduction').value=g.spawnDelayReduction;$('round-gold-base').value=g.roundGoldBase;$('round-gold-growth').value=g.roundGoldGrowth;$('speed-base').value=g.speedBase;$('speed-growth').value=g.speedGrowth}
  function applyVariables(){const g=cfg.game;cfg.map.name=$('map-name').value.trim()||'untitled-map';g.waves=Math.max(1,+$('waves').value||50);g.enemiesPerWave=Math.max(1,+$('enemies').value||6);g.enemiesPerWaveGrowth=Math.max(0,+$('enemy-growth').value||0);g.startingGold=Math.max(0,+$('starting-gold').value||0);g.startingLives=Math.max(1,+$('starting-lives').value||1);g.baseSpawnDelay=Math.max(1,+$('spawn-delay').value||45);g.minimumSpawnDelay=Math.max(1,+$('minimum-spawn-delay').value||10);g.spawnDelayReduction=Math.max(0,+$('spawn-delay-reduction').value||0);g.roundGoldBase=Math.max(0,+$('round-gold-base').value||0);g.roundGoldGrowth=Math.max(0,+$('round-gold-growth').value||0);g.speedBase=Math.max(.1,+$('speed-base').value||1);g.speedGrowth=Math.max(0,+$('speed-growth').value||0)}
  function renderTools(){$('tools').innerHTML=tools.map(([name,value,,hint])=>`<button class="tool ${tool===value?'active':''}" data-tool="${value}">${name}<br><small>${hint}</small></button>`).join('');$('tools').querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{tool=+b.dataset.tool;renderTools()})}
  function input(name,label,type='number'){const value=cfg.towers[towerKey][name]??'';return`<label>${label}</label><input data-field="${name}" type="${type}" ${type==='number'?'step=".01"':''} value="${esc(value)}">`}
  function renderTowers(){$('towers').innerHTML=Object.entries(cfg.towers).map(([key,t])=>`<button class="tower ${key===towerKey?'active':''}" data-tower="${key}">${esc(t.name)}<br><small>${esc(t.effect)} | ${t.projectileCount||1} projectile</small></button>`).join('');$('towers').querySelectorAll('[data-tower]').forEach(b=>b.onclick=()=>{towerKey=b.dataset.tower;renderTowers()});const t=cfg.towers[towerKey];$('tower-fields').innerHTML=input('name','Tower name','text')+input('color','Model color','color')+input('projectileColor','Projectile color','color')+input('cost','Cost')+input('damage','Damage')+input('range','Range')+input('fireRate','Rate of fire in frames')+input('projectileSpeed','Projectile speed')+input('projectileSize','Projectile size')+input('projectileCount','Projectiles per shot')+input('spread','Multishot spread')+`<label>Effect preset</label><select data-field="effect">${Object.keys(effectFields).map(v=>`<option ${v===t.effect?'selected':''}>${v}</option>`).join('')}</select>`+(effectFields[t.effect]||[]).map(([n,l])=>input(n,l)).join('');$('tower-fields').querySelectorAll('[data-field]').forEach(field=>field.onchange=()=>{t[field.dataset.field]=field.type==='number'?+field.value:field.value;renderTowers()})}
  function bindColor(inputId,textId,paletteId){const picker=$(inputId),text=$(textId),box=$(paletteId),set=value=>{if(!/^#[0-9a-f]{6}$/i.test(value))return;picker.value=value;text.value=value.toLowerCase()};picker.oninput=()=>set(picker.value);text.onchange=()=>set(text.value);box.innerHTML=palette.map(color=>`<button class="swatch" type="button" data-color="${color}" style="background:${color}" title="${color}"></button>`).join('');box.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>set(b.dataset.color))}
  function creatorNumber(name,label,value){return`<label>${label}</label><input data-create-field="${name}" type="number" step=".01" value="${esc(value)}">`}
  function fillCreator(presetKey){const p=projectilePresets.find(x=>x[0]===presetKey)||projectilePresets[0],extras=p[5];$('create-model').value=p[2];$('create-projectile-color').value=p[4];$('create-projectile-color-text').value=p[4];$('create-fields').innerHTML=baseFields.map(([n,l,v])=>creatorNumber(n,l,v)).join('')+`<label>Effect preset</label><input value="${esc(p[3])}" disabled>`+(effectFields[p[3]]||[]).map(([n,l])=>creatorNumber(n,l,extras[n]??0)).join('')}
  function openCreator(){$('tower-modal').hidden=false;$('create-name').focus()}
  function closeCreator(){$('tower-modal').hidden=true}
  function createTower(){const preset=projectilePresets.find(p=>p[0]===$('create-projectile').value)||projectilePresets[0],key='custom_'+Date.now().toString(36),tower={name:$('create-name').value.trim()||'Custom Tower',icon:$('create-icon').value.trim().slice(0,2)||'N',model:$('create-model').value,color:$('create-color').value,projectileColor:$('create-projectile-color').value,effect:preset[3],description:$('create-description').value.trim()||'A custom map tower.',upgradeCosts:[75,150,300,600],upgradeDamage:[8,12,18,28],upgradeRange:[15,20,25,35],upgradeFireRate:[-8,-10,-12,-15]};$('create-fields').querySelectorAll('[data-create-field]').forEach(field=>tower[field.dataset.createField]=+field.value||0);cfg.towers[key]=tower;towerKey=key;closeCreator();renderTowers();tell(`Added ${tower.name} to the end of the tower list.`)}
  function resizeCanvas(){canvas.width=stage.clientWidth;canvas.height=stage.clientHeight;draw()}addEventListener('resize',resizeCanvas);
  function draw(){ctx.fillStyle='#090b16';ctx.fillRect(0,0,canvas.width,canvas.height);const s=view.size;for(let r=0;r<cfg.map.height;r++)for(let c=0;c<cfg.map.width;c++){const x=c*s-view.x,y=r*s-view.y;if(x+s<0||y+s<0||x>canvas.width||y>canvas.height)continue;const v=cfg.map.tiles[r][c];ctx.fillStyle=tools[v]?.[2]||tools[0][2];ctx.fillRect(x,y,s,s);ctx.strokeStyle='#ffffff19';ctx.strokeRect(x,y,s,s);if(v===TILES.BLOCK){ctx.fillStyle='#687760';ctx.fillRect(x+4,y+4,s-8,s-8)}if(v===TILES.START||v===TILES.END){ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(10,s*.42)}px Arial`;ctx.fillText(v===TILES.START?'S':'E',x+s*.32,y+s*.68)}}}
  function cell(e){const b=canvas.getBoundingClientRect();return[Math.floor((e.clientX-b.left+view.x)/view.size),Math.floor((e.clientY-b.top+view.y)/view.size)]}
  function paint(e){const[c,r]=cell(e);if(c<0||r<0||c>=cfg.map.width||r>=cfg.map.height)return;if(tool===TILES.START||tool===TILES.END)for(const row of cfg.map.tiles)for(let x=0;x<row.length;x++)if(row[x]===tool)row[x]=TILES.GRASS;cfg.map.tiles[r][c]=tool;draw()}
  canvas.onmousedown=e=>{if(e.button===2){mouse.pan=true;mouse.x=e.clientX;mouse.y=e.clientY}else{mouse.paint=true;paint(e)}};canvas.onmousemove=e=>{if(mouse.paint)paint(e);if(mouse.pan){view.x-=e.clientX-mouse.x;view.y-=e.clientY-mouse.y;mouse.x=e.clientX;mouse.y=e.clientY;draw()}};addEventListener('mouseup',()=>mouse.paint=mouse.pan=false);canvas.oncontextmenu=e=>e.preventDefault();canvas.onwheel=e=>{e.preventDefault();view.size=Math.max(9,Math.min(68,view.size*(1-e.deltaY*.001)));draw()};
  function findPath(){let start,end;for(let r=0;r<cfg.map.height;r++)for(let c=0;c<cfg.map.width;c++){if(cfg.map.tiles[r][c]===TILES.START)start=[c,r];if(cfg.map.tiles[r][c]===TILES.END)end=[c,r]}if(!start||!end)return null;const queue=[start],seen=new Set([start.join(',')]),parent=new Map();for(let i=0;i<queue.length;i++){const current=queue[i],key=current.join(',');if(key===end.join(',')){const path=[];let node=key;while(node){path.unshift(node.split(',').map(Number));node=parent.get(node)}return path}for(const[dc,dr]of[[1,0],[-1,0],[0,1],[0,-1]]){const c=current[0]+dc,r=current[1]+dr,k=`${c},${r}`,v=cfg.map.tiles[r]?.[c];if(!seen.has(k)&&(v===TILES.PATH||v===TILES.START||v===TILES.END)){seen.add(k);parent.set(k,key);queue.push([c,r])}}}return null}
  function prepare(){applyVariables();const path=findPath();if(!path){tell('Add one connected Start -> Path -> End route before saving.');return false}cfg.map.path=path;cfg.map.cameraStart={col:path[0][0],row:path[0][1]};return true}
  function useConfig(data,message){if(!data?.map?.tiles||!data?.towers||!data?.game)throw Error('invalid map');cfg=data;towerKey=Object.keys(cfg.towers)[0];sync();renderTowers();draw();tell(message)}
  function renderMaps(){const fs=api(),box=$('saved-maps');if(!fs){box.innerHTML='<small>Browser mode keeps a local draft. Launch the editor app for NimTD/maps files.</small>';return}const files=fs.list();box.innerHTML=files.length?files.map(name=>`<div class="row"><button class="btn" data-load="${esc(name)}">${esc(name)}</button><button class="btn danger" data-delete="${esc(name)}">X</button></div>`).join(''):'<small>No files in NimTD/maps yet.</small>';box.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{try{useConfig(fs.load(b.dataset.load),`Loaded maps/${b.dataset.load}`)}catch{tell('Could not load that map file.')}});box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm(`Delete ${b.dataset.delete}?`)){fs.delete(b.dataset.delete);renderMaps();tell(`Deleted maps/${b.dataset.delete}`)}})}
  $('resize').onclick=()=>{const w=Math.max(5,Math.min(100,+$('width').value||42)),h=Math.max(5,Math.min(100,+$('height').value||30)),old=cfg.map.tiles;cfg.map.width=w;cfg.map.height=h;cfg.map.tiles=Array.from({length:h},(_,r)=>Array.from({length:w},(_,c)=>old[r]?.[c]??TILES.GRASS));sync();draw();tell(`Grid resized to ${w} x ${h}.`)};
  $('save').onclick=()=>{if(!prepare())return;localStorage.setItem('nimtd.editorDraft',JSON.stringify(cfg));const fs=api();if(fs){const file=fs.save(cfg.map.name,cfg);fs.setDefault(cfg);renderMaps();tell(`Saved maps/${file} and set it as the default map.`)}else tell('Local browser draft saved. Launch the editor app to write NimTD/maps.')};
  $('open-folder').onclick=()=>{const fs=api();if(fs)fs.openFolder().catch(error=>tell(`Could not open maps folder: ${error.message}`));else tell('Launch the editor app to open NimTD/maps in File Explorer.')};
  $('test').onclick=()=>{if(!prepare())return;localStorage.setItem('nimtd.editorDraft',JSON.stringify(cfg));localStorage.setItem('nimtd.activeConfig',JSON.stringify(cfg));const fs=api();if(fs){fs.save(cfg.map.name,cfg);fs.setDefault(cfg)}location.href='game.html'};
  $('game').onclick=()=>location.href='index.html';$('export').onclick=()=>{if(!prepare())return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(cfg,null,2)],{type:'application/json'}));a.download=cfg.map.name.replace(/\W+/g,'-')+'.nimmaps';a.click();URL.revokeObjectURL(a.href)};
  $('import').onclick=()=>$('file').click();$('file').onchange=e=>{const reader=new FileReader();reader.onload=()=>{try{useConfig(JSON.parse(reader.result),'JSON imported.')}catch{tell('Invalid NimTD map JSON.')}};reader.readAsText(e.target.files[0])};
  $('create-model').innerHTML=models.map(model=>`<option>${model}</option>`).join('');$('create-projectile').innerHTML=projectilePresets.map(([key,label,,effect])=>`<option value="${key}">${label} | ${effect}</option>`).join('');$('create-projectile').onchange=()=>fillCreator($('create-projectile').value);$('new-tower').onclick=openCreator;$('tower-cancel').onclick=$('tower-cancel-top').onclick=closeCreator;$('tower-create').onclick=createTower;$('tower-modal').onclick=e=>{if(e.target===$('tower-modal'))closeCreator()};addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('tower-modal').hidden)closeCreator()});bindColor('create-color','create-color-text','tower-palette');bindColor('create-projectile-color','create-projectile-color-text','projectile-palette');fillCreator('basic');
  sync();renderTools();renderTowers();renderMaps();resizeCanvas();
})();
