(function () {
  const {TILES,clone,createNormalMap,gameValues,towers,effects}=window.NimTD, canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),TILE=gameValues.tileSize,TAU=Math.PI*2;
  const id=x=>document.getElementById(x), spriteCache=new Map();
  function normalConfig(){return{version:4,map:createNormalMap(),game:clone(gameValues),towers:clone(towers)}}
  function defaultConfig(){try{return window.electronAPI?.maps?.loadDefault()||normalConfig()}catch{return normalConfig()}}
  function getConfig(){try{return JSON.parse(localStorage.getItem('nimtd.activeConfig'))||defaultConfig()}catch{return defaultConfig()}}
  function compact(a,keep){let w=0;for(let r=0;r<a.length;r++)if(keep(a[r]))a[w++]=a[r];a.length=w}
  function sprite(key,size,draw){if(spriteCache.has(key))return spriteCache.get(key);const c=document.createElement('canvas');c.width=c.height=size;draw(c.getContext('2d'),size);spriteCache.set(key,c);return c}
  function particleSprite(color){return sprite('p'+color,16,(g,s)=>{g.fillStyle=color;g.beginPath();g.arc(s/2,s/2,s/2-1,0,TAU);g.fill()})}
  function projectileSprite(color){return sprite('b'+color,40,(g,s)=>{const c=s/2;g.fillStyle=color+'66';g.beginPath();g.arc(c,c,20,0,TAU);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(c,c,6,0,TAU);g.fill();g.fillStyle=color;g.beginPath();g.arc(c,c,10,0,TAU);g.fill()})}
  class Game {
    constructor(config){
      this.config=config;this.map=config.map;this.game=config.game;this.defs=config.towers;this.path=this.map.path;this.pathSet=new Set(this.path.map(p=>p.join(',')));
      this.towers=[];this.enemies=[];this.projectiles=[];this.aoeZones=[];this.particles=[];this.trails=[];this.chains=[];this.starEffects=[];
      this.gold=this.game.startingGold;this.lives=this.game.startingLives;this.score=0;this.round=1;this.speed=this.game.speedBase;this.over=false;this.spawned=0;this.spawnTimer=0;this.spawnDelay=this.game.baseSpawnDelay;
      this.selectedType=null;this.selectedTower=null;this.keys={};this.mouse={col:-1,row:-1};const start=this.path[0];this.camera={x:start[0]*TILE-200,y:start[1]*TILE-200,vx:0,vy:0,zoom:.85,targetZoom:.85,minZoom:.4,maxZoom:1.8};
      this.resize();this.bind();this.panel();requestAnimationFrame(()=>this.loop());
    }
    resize(){canvas.width=innerWidth;canvas.height=innerHeight}
    bind(){
      addEventListener('resize',()=>this.resize());addEventListener('keydown',e=>{this.keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='e')location.href='editor.html'});addEventListener('keyup',e=>this.keys[e.key.toLowerCase()]=false);
      canvas.onwheel=e=>{e.preventDefault();this.camera.targetZoom=Math.max(this.camera.minZoom,Math.min(this.camera.maxZoom,this.camera.targetZoom-e.deltaY*.001))};
      canvas.oncontextmenu=e=>{e.preventDefault();this.selectedType=null;this.selectedTower=null;this.panel()};
      canvas.onmousemove=e=>{const w=this.world(e.clientX,e.clientY);this.mouse.col=Math.floor(w.x/TILE);this.mouse.row=Math.floor(w.y/TILE)};
      canvas.onmousedown=e=>{if(e.button!==0)return;const{col,row}=this.mouse;if(!this.inside(col,row))return;const tower=this.towers.find(t=>t.col===col&&t.row===row);if(tower){this.selectedTower=tower;this.selectedType=null;this.panel();return}if(this.selectedType)this.place(col,row,this.selectedType)};
      id('open-maps').onclick=()=>this.openMaps();id('open-editor').onclick=()=>location.href='editor.html';
    }
    inside(c,r){return c>=0&&r>=0&&c<this.map.width&&r<this.map.height}
    canBuild(c,r){return this.inside(c,r)&&this.map.tiles[r][c]===TILES.GRASS&&!this.towers.some(t=>t.col===c&&t.row===r)}
    world(x,y){return{x:(x-canvas.width/2)/this.camera.zoom+this.camera.x,y:(y-canvas.height/2)/this.camera.zoom+this.camera.y}}
    screen(x,y){return{x:(x-this.camera.x)*this.camera.zoom+canvas.width/2,y:(y-this.camera.y)*this.camera.zoom+canvas.height/2}}
    distSq(a,b){const x=a.x-b.x,y=a.y-b.y;return x*x+y*y}
    waveCount(){return this.game.enemiesPerWave+Math.floor(this.round*(this.game.enemiesPerWaveGrowth??1.4))}
    openMaps(){const api=window.electronAPI?.maps,box=id('map-list');if(!api){box.innerHTML='<div class="tower-desc">Launch with launch.bat to browse the maps folder.</div>';return}try{const config=api.choose();if(!config)return;localStorage.setItem('nimtd.activeConfig',JSON.stringify(config));location.reload()}catch(error){box.innerHTML=`<div class="tower-desc">Could not load map: ${error.message}</div>`}}
    panel(){
      id('buy-list').innerHTML=Object.entries(this.defs).map(([k,d])=>`<div class="tower-option${this.gold<d.cost?' disabled':''}${this.selectedType===k?' selected':''}" data-type="${k}"><div><div class="tower-name"><span class="tower-mark" style="color:${d.color}">${d.icon}</span> ${d.name}</div><div class="tower-desc">${d.description}</div></div><div class="tower-cost">${d.cost}g</div></div>`).join('');
      id('buy-list').querySelectorAll('.tower-option:not(.disabled)').forEach(b=>b.onclick=()=>{this.selectedType=this.selectedType===b.dataset.type?null:b.dataset.type;this.selectedTower=null;this.panel()});
      const t=this.selectedTower,d=t&&this.defs[t.type],stats=id('tower-stats'),up=id('upgrade-list');if(!t){stats.textContent=this.selectedType?'Click a buildable tile to place tower.':'';up.innerHTML='';return}
      stats.innerHTML=`<b>${d.name}</b> Lv.${t.level+1}<br>DMG ${t.damage} | RNG ${t.range} | RATE ${t.fireRate}f<br>${effects.registry[t.effect]?.label||t.effect}`;
      const cost=d.upgradeCosts[t.level],canUpgrade=t.level<4&&this.gold>=cost;up.innerHTML=(t.level<4?`<button class="panel-btn${canUpgrade?'':' disabled'}" id="upgrade"${canUpgrade?'':' disabled'}>Upgrade <span>${cost}g</span></button>`:'<div class="maxed">MAX LEVEL</div>')+`<button class="panel-btn sell" id="sell">Sell <span>60%</span></button>`;
      if(id('upgrade'))id('upgrade').onclick=()=>this.upgrade(t);id('sell').onclick=()=>this.sell(t)
    }
    place(col,row,type){const d=this.defs[type];if(!d||this.gold<d.cost||!this.canBuild(col,row))return;this.gold-=d.cost;const tower={...clone(d),type,col,row,x:(col+.5)*TILE,y:(row+.5)*TILE,level:0,cooldown:0,angle:0};this.towers.push(tower);this.selectedType=null;this.selectedTower=tower;this.panel()}
    upgrade(t){const d=this.defs[t.type],cost=d.upgradeCosts[t.level];if(t.level>=4||this.gold<cost)return;this.gold-=cost;t.damage+=d.upgradeDamage[t.level];t.range+=d.upgradeRange[t.level];t.fireRate=Math.max(5,t.fireRate+d.upgradeFireRate[t.level]);if(t.effect==='chain')t.chainCount++;t.level++;this.panel()}
    sell(t){const d=this.defs[t.type];let total=d.cost;for(let i=0;i<t.level;i++)total+=d.upgradeCosts[i];this.gold+=Math.floor(total*.6);this.towers=this.towers.filter(x=>x!==t);this.selectedTower=null;this.panel()}
    spawnParticles(x,y,color,count){for(let i=0;i<count;i++){const a=Math.random()*TAU,s=1+Math.random()*4;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:20+Math.random()*20,maxLife:40,color,size:1+Math.random()*2.5})}}
    createEnemy(){const p=this.round/this.game.waves,types=[{type:'basic',color:'#ff4444',size:8,hp:30+p*300,speed:1.2+p,gold:5+Math.floor(p*15),score:10+Math.floor(p*20)}];if(this.round>=3)types.push({type:'fast',color:'#ffaa00',size:6,hp:15+p*150,speed:2.5+p*1.8,gold:8+Math.floor(p*20),score:15+Math.floor(p*25)});if(this.round>=6)types.push({type:'tank',color:'#8844ff',size:13,hp:120+p*800,speed:.7+p*.3,gold:15+Math.floor(p*30),score:25+Math.floor(p*40)});if(this.round>=12)types.push({type:'healer',color:'#44ff88',size:9,hp:50+p*350,speed:1+p*.6,gold:20+Math.floor(p*35),score:30+Math.floor(p*45),heals:true,healAmount:3+p*10,healRange:80});if(this.round%5===0)types.push({type:'boss',color:'#ff0066',size:18,hp:500+p*3000,speed:.5+p*.3,gold:50+Math.floor(p*100),score:100+Math.floor(p*200)});const v=types[Math.floor(Math.random()*types.length)],m=1+(this.round-1)*.18,start=this.path[0];return{...v,hp:Math.floor(v.hp*m),maxHp:Math.floor(v.hp*m),x:(start[0]+.5)*TILE,y:(start[1]+.5)*TILE,pathIndex:0,alive:true,slowed:0,stunned:0,burning:0,burnDmg:0,poisoned:0,poisonedDuration:0,poisonedDamage:0}}
    killEnemy(e,particles=12){if(!e.alive)return;e.alive=false;this.gold+=e.gold;this.score+=e.score;this.spawnParticles(e.x,e.y,e.color,particles)}
    target(t){let best=null,progress=-1,near=Infinity,range=t.range*t.range;for(const e of this.enemies){const d=this.distSq(t,e);if(e.alive&&d<=range&&(e.pathIndex>progress||(e.pathIndex===progress&&d<near))){best=e;progress=e.pathIndex;near=d}}return best}
    shoot(t,e){const count=Math.max(1,t.projectileCount||1),spread=t.spread??.5,base=Math.atan2(e.y-t.y,e.x-t.x);for(let i=0;i<count;i++){const a=base+(i-(count-1)/2)*(count===1?0:spread/(count-1));this.projectiles.push({x:t.x,y:t.y,vx:Math.cos(a)*t.projectileSpeed,vy:Math.sin(a)*t.projectileSpeed,damage:t.damage,color:t.projectileColor,size:t.projectileSize,tower:t,target:count===1?e:null,hit:false})}t.angle=base}
    chainLightning(source,damage,count,range){if(count<=0)return;let next=null,best=range*range;for(const e of this.enemies){const d=this.distSq(source,e);if(e!==source&&e.alive&&d<best){best=d;next=e}}if(!next)return;next.hp-=damage;this.spawnParticles(next.x,next.y,'#88ccff',8);this.chains.push({x1:source.x,y1:source.y,x2:next.x,y2:next.y,life:15,maxLife:15});if(next.hp<=0)this.killEnemy(next);this.chainLightning(next,damage*.6,count-1,range)}
    update(){
      if(this.over)return;const c=this.camera,sm=this.speed,cam=6;if(this.keys.w||this.keys.arrowup)c.vy=-cam;else if(this.keys.s||this.keys.arrowdown)c.vy=cam;else c.vy*=.85;if(this.keys.a||this.keys.arrowleft)c.vx=-cam;else if(this.keys.d||this.keys.arrowright)c.vx=cam;else c.vx*=.85;c.x+=c.vx/c.zoom;c.y+=c.vy/c.zoom;c.zoom+=(c.targetZoom-c.zoom)*.12;
      this.spawnTimer+=sm;if(this.spawnTimer>=this.spawnDelay){this.spawnTimer=0;if(this.spawned<this.waveCount()){this.enemies.push(this.createEnemy());this.spawned++}else if(!this.enemies.length){this.gold+=this.game.roundGoldBase+this.round*this.game.roundGoldGrowth;this.round++;if(this.round>this.game.waves)this.over=true;else{this.spawned=0;this.spawnDelay=Math.max(this.game.minimumSpawnDelay,this.game.baseSpawnDelay-this.round*this.game.spawnDelayReduction)}}}
      for(const e of this.enemies){if(!e.alive)continue;if(e.stunned>0){e.stunned-=sm;continue}let move=e.speed*sm;if(e.slowed>0){move*=.4;e.slowed-=sm}if(e.pathIndex<this.path.length-1){const p=this.path[e.pathIndex+1],tx=(p[0]+.5)*TILE,ty=(p[1]+.5)*TILE,dx=tx-e.x,dy=ty-e.y,d=Math.hypot(dx,dy);if(d<move){e.x=tx;e.y=ty;e.pathIndex++}else{e.x+=dx/d*move;e.y+=dy/d*move}}else{e.alive=false;this.lives--;this.spawnParticles(e.x,e.y,'#ff4444',15);if(this.lives<=0)this.over=true}if(e.heals&&e.alive)for(const o of this.enemies)if(o!==e&&o.alive&&this.distSq(e,o)<e.healRange*e.healRange)o.hp=Math.min(o.maxHp,o.hp+e.healAmount*sm*.016);if(e.burning>0){e.hp-=e.burnDmg*sm*.016;e.burning-=sm}if(e.poisonedDuration>0){e.hp-=e.poisonedDamage*e.poisoned*sm*.016;e.poisonedDuration-=sm;if(e.poisonedDuration<=0)e.poisoned=0}if(e.hp<=0)this.killEnemy(e)}
      compact(this.enemies,e=>e.alive);
      for(const t of this.towers){t.cooldown-=sm;if(t.cooldown<=0){const e=this.target(t);if(e){this.shoot(t,e);t.cooldown=t.fireRate}}}
      const maxX=this.map.width*TILE+200,maxY=this.map.height*TILE+200,piercing={piercing:1,laser:1,reflect:1};for(const p of this.projectiles){if(p.hit)continue;p.x+=p.vx*sm;p.y+=p.vy*sm;if(p.x<-200||p.y<-200||p.x>maxX||p.y>maxY){p.hit=true;continue}if(p.tower.effect==='trail')this.trails.push({x:p.x,y:p.y,color:p.color,size:3+Math.random()*2,life:12,maxLife:12});let hit=null;if(p.target?.alive&&!p.hitList?.has(p.target)&&this.distSq(p,p.target)<256)hit=p.target;else if(!p.target||piercing[p.tower.effect])for(const e of this.enemies)if(e.alive&&!p.hitList?.has(e)&&this.distSq(p,e)<196){hit=e;break}if(hit){if(piercing[p.tower.effect]){p.hitList=p.hitList||new Set();p.hitList.add(hit);if(p.hitList.size>=(p.tower.pierceCount||3))p.hit=true}else p.hit=true;effects.apply[p.tower.effect]?.(this,p,hit)}}compact(this.projectiles,p=>!p.hit);
      for(const z of this.aoeZones){z.duration-=sm;z.tickTimer-=sm;if(z.effect==='radiation'&&z.radius<z.maxRadius)z.radius=Math.min(z.maxRadius,z.radius+z.expandRate*sm);if(z.tickTimer<=0){z.tickTimer=z.tickInterval||30;for(const e of this.enemies)if(e.alive&&this.distSq(z,e)<z.radius*z.radius){if(z.effect==='web')e.slowed=Math.max(e.slowed,40);else{e.hp-=z.damage;e.burning=60;e.burnDmg=Math.floor(z.damage*.3);this.spawnParticles(e.x,e.y,'#ff4422',3);if(e.hp<=0)this.killEnemy(e)}}}}compact(this.aoeZones,z=>z.duration>0);
      for(const p of this.particles){p.x+=p.vx*sm;p.y+=p.vy*sm;p.life-=sm}compact(this.particles,p=>p.life>0);for(const p of this.trails)p.life-=sm;compact(this.trails,p=>p.life>0);for(const p of this.chains)p.life-=sm;compact(this.chains,p=>p.life>0);for(const p of this.starEffects)p.life-=sm;compact(this.starEffects,p=>p.life>0);this.speed=this.game.speedBase+(this.round-1)*this.game.speedGrowth
    }
    tile(c,r,x,y,s){const v=this.map.tiles[r][c];if(v===TILES.PATH||v===TILES.START||v===TILES.END){ctx.fillStyle='#5a4a3a';ctx.fillRect(x,y,s,s);ctx.fillStyle='#6b5b4b';ctx.fillRect(x+2,y+2,s-4,s-4);ctx.fillStyle='#3a2a1a';ctx.fillRect(x,y+s-3,s,3);ctx.fillStyle='#7a6a5a';ctx.fillRect(x,y,s,2)}else if(v===TILES.BLOCK){ctx.fillStyle='#3a4a3a';ctx.fillRect(x,y,s,s);ctx.fillStyle='#5a5a4a';ctx.fillRect(x+4,y+4,s-8,s-8);ctx.fillStyle='#6a6a5a';ctx.fillRect(x+6,y+6,s-12,s-12)}else{ctx.fillStyle=(c+r)%2?'#335533':'#3a5533';ctx.fillRect(x,y,s,s);ctx.strokeStyle='#ffffff0a';ctx.strokeRect(x,y,s,s)}}
    draw(){
      ctx.fillStyle='#0a0a15';ctx.fillRect(0,0,canvas.width,canvas.height);const z=this.camera.zoom,s=TILE*z,a=this.world(0,0),b=this.world(canvas.width,canvas.height);for(let r=Math.max(0,Math.floor(a.y/TILE)-1);r<=Math.min(this.map.height-1,Math.ceil(b.y/TILE)+1);r++)for(let c=Math.max(0,Math.floor(a.x/TILE)-1);c<=Math.min(this.map.width-1,Math.ceil(b.x/TILE)+1);c++){const p=this.screen(c*TILE,r*TILE);this.tile(c,r,p.x,p.y,s)}
      for(const zone of this.aoeZones){const p=this.screen(zone.x,zone.y),r=zone.radius*z,alpha=zone.duration/zone.maxDuration*.5,g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r);g.addColorStop(0,`rgba(255,100,30,${alpha})`);g.addColorStop(.7,`rgba(255,60,10,${alpha*.5})`);g.addColorStop(1,'rgba(255,20,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,r,0,TAU);ctx.fill()}
      for(const e of this.chains){const a=this.screen(e.x1,e.y1),b=this.screen(e.x2,e.y2);ctx.strokeStyle=`rgba(136,204,255,${e.life/e.maxLife})`;ctx.lineWidth=2*z;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo((a.x+b.x)/2+(Math.random()-.5)*20*z,(a.y+b.y)/2+(Math.random()-.5)*20*z,b.x,b.y);ctx.stroke()}
      for(const e of this.starEffects){const p=this.screen(e.x,e.y),alpha=e.life/e.maxLife;ctx.strokeStyle=`rgba(255,230,120,${alpha})`;ctx.beginPath();for(let i=0;i<10;i++){const r=(i%2?11:22)*z,a=-Math.PI/2+i*Math.PI/5,x=p.x+Math.cos(a)*r,y=p.y+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}
      for(const t of this.towers){const p=this.screen(t.x,t.y),sz=TILE*z;window.NimTD.towerModels.render(ctx,p,sz,t);if(t===this.selectedTower){ctx.strokeStyle='#ffffff66';ctx.setLineDash([4,4]);ctx.beginPath();ctx.arc(p.x,p.y,t.range*z,0,TAU);ctx.stroke();ctx.setLineDash([])}}
      for(const e of this.enemies){const p=this.screen(e.x,e.y),sz=e.size*z;ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(p.x,p.y+sz*.3,sz*.8,sz*.3,0,0,TAU);ctx.fill();const g=ctx.createRadialGradient(p.x-sz*.2,p.y-sz*.2,sz*.1,p.x,p.y,sz*.7);g.addColorStop(0,'#fff');g.addColorStop(.4,e.color);g.addColorStop(1,'#000');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,sz*.55,0,TAU);ctx.fill();ctx.fillStyle='#333';ctx.fillRect(p.x-sz*.6,p.y-sz*.9,sz*1.2,4*z);ctx.fillStyle='#55ee66';ctx.fillRect(p.x-sz*.6,p.y-sz*.9,sz*1.2*Math.max(0,e.hp/e.maxHp),4*z)}
      for(const p of this.projectiles){const q=this.screen(p.x,p.y),sz=p.size*z;ctx.drawImage(projectileSprite(p.color),q.x-sz*2,q.y-sz*2,sz*4,sz*4)}for(const p of [...this.trails,...this.particles]){const q=this.screen(p.x,p.y),sz=p.size*z;ctx.globalAlpha=p.life/p.maxLife;ctx.drawImage(particleSprite(p.color),q.x-sz,q.y-sz,sz*2,sz*2)}ctx.globalAlpha=1;
      if(this.selectedType&&this.inside(this.mouse.col,this.mouse.row)){const p=this.screen(this.mouse.col*TILE,this.mouse.row*TILE);ctx.fillStyle=this.canBuild(this.mouse.col,this.mouse.row)?'#00ff6444':'#ff000055';ctx.fillRect(p.x,p.y,s,s)}
      id('lives').textContent=`Lives ${this.lives}`;id('score').textContent=`Score ${this.score}`;id('gold').textContent=`Gold ${this.gold}`;id('round-info').textContent=`Round ${Math.min(this.round,this.game.waves)}/${this.game.waves}`;id('speed-indicator').textContent=`Speed ${this.speed.toFixed(1)}x`;
      if(this.over){ctx.fillStyle='#000b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle=this.lives<=0?'#ff4444':'#ffdd00';ctx.font='bold 48px Arial';ctx.textAlign='center';ctx.fillText(this.lives<=0?'GAME OVER':'VICTORY',canvas.width/2,canvas.height/2)}
    }
    loop(){this.update();this.draw();requestAnimationFrame(()=>this.loop())}
  }
  window.NimTD.game=new Game(getConfig());
})();
